version: 2.1

orbs:
  slack: circleci/slack@4.4.2
  node: circleci/node@4.5.1
  jq: circleci/jq@2.2.0
  ld-common-circleci: littledata/ld-common-circleci@0.0.25

slack-notifications: &slack-notifications
  post-steps:
    - ld-common-circleci/notify-fail
jobs:
  install_npm:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum ".circleci/config.yml" }}-{{ checksum "package-lock.json" }}
      - node/install-npm
      - node/install-packages
      - save_cache:
          key: deps-{{ checksum ".circleci/config.yml" }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
  deploy_prod:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - jq/install
      - restore_cache:
          keys:
            - deps-{{ checksum ".circleci/config.yml" }}-{{ checksum "package-lock.json" }}
      - run: npx webpack --config webpack.config.js
      - run: git archive -o pointless.zip HEAD:dist/
      - run: |
          ACCESS_TOKEN=$(curl "https://accounts.google.com/o/oauth2/token" -d "client_id=865001279170-7isl21j6rhk1ej2ci5vj8kkvqmib172o.apps.googleusercontent.com&client_secret=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&code=4/0AdQt8qgebQdGJmRnxsjMFwQ8A_c07A3HE-u72d5gr65tmTdttrJo6dqF7YPMmyroOH6-5A&grant_type=authorization_code&redirect_uri=urn:ietf:wg:oauth:2.0:oob" | jq '.refresh_token')
          echo $ACCESS_TOKEN 
          curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -X PUT -T pointless.zip -v "https://www.googleapis.com/upload/chromewebstore/v1.1/items/${APP_ID}"
          curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -H "Content-Length: 0" -X POST -v "https://www.googleapis.com/chromewebstore/v1.1/items/${APP_ID}/publish"
workflows:
  main:
    jobs:
      - install_npm
      - deploy_prod:
          <<: *slack-notifications
          requires:
            - install_npm
          filters:
            branches:
              only: master