version: 2.1

orbs:
  slack: circleci/slack@4.4.2
  node: circleci/node@4.5.1
  jq: circleci/jq@2.2.0
  ld-common-circleci: littledata/ld-common-circleci@0.0.25

slack-notifications: &slack-notifications
  post-steps:
    - ld-common-circleci/notify-fail
jobs:
  deploy_prod:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - jq/install
      - run: git archive -o pointless.zip HEAD
      - run: 'export ACCESS_TOKEN=$(curl "https://accounts.google.com/o/oauth2/token" -d "client_id=${CLIENT_ID}&client_secret=${CLIENT_SECRET}&refresh_token=${REFRESH_TOKEN}&grant_type=refresh_token&redirect_uri=urn:ietf:wg:oauth:2.0:oob" | jq -r .access_token)' >> $BASH_ENV
      - run: echo $ACCESS_TOKEN
      - run: 'curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -X PUT -T pointless.zip -v "https://www.googleapis.com/upload/chromewebstore/v1.1/items/${APP_ID}"'
      - run: 'curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -H "Content-Length: 0" -X POST -v "https://www.googleapis.com/chromewebstore/v1.1/items/${APP_ID}/publish"'
workflows:
  main:
    jobs:
      - deploy_prod:
          <<: *slack-notifications
          filters:
            branches:
              only: master